In [43]:
from typing import List, Dict, Tuple
from datetime import datetime
import pandas as pd
import numpy as np
from dataclasses import dataclass
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from encode import DataEncoder

In [44]:
data = pd.read_csv("./data.csv", index_col = 0)

In [46]:
data = DataEncoder(data).encode(
    col_type_dict = {
        "div": "one_hot",
        "hometeam": "one_hot",
        "awayteam": "one_hot",
        "referee": "one_hot"
    }
)

,date,time,fthg,ftag,ftr,htr,hs,as,hst,ast,...,referee_S Attwell,referee_S Duncan,referee_S Hooper,referee_S Martin,referee_S Scott,referee_T Bramall,referee_T Harrington,referee_T Robinson,referee_k Stroud,date_enc
0,2019-08-02,19:45,3,3,D,D,12,17,4,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,2019-08-03,15:00,1,0,H,H,17,15,4,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,2019-08-03,15:00,1,2,A,A,14,9,2,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,2019-08-03,15:00,0,1,A,A,15,1,3,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,2019-08-03,15:00,1,0,H,H,8,5,3,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2791,2021-05-08,12:30,0,3,A,A,5,16,0,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,645
2792,2021-05-08,12:30,1,2,A,H,16,7,3,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,645
2793,2021-05-08,12:30,3,1,H,D,9,17,4,4,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,645
2794,2021-05-08,12:30,2,2,D,H,13,11,7,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,645
2795,2021-05-08,12:30,2,0,H,D,10,15,3,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,645